spring.datasource.url=jdbc:postgresql://116.63.46.160:5432/belt_dev?stringtype=unspecified&TimeZone=UTC
spring.datasource.username=product_developer
spring.datasource.password=product_developer
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.validation-timeout=60000

spring.redis.host=116.63.46.160
spring.redis.port=6379
spring.redis.database=11
spring.redis.password=h@9Yq~8Ya@9Sn!0J

spring.mqtt.server-uri=tcp://116.63.46.160:1883
spring.mqtt.username=admin
spring.mqtt.password=public
spring.mqtt.automatic-reconnect=true


ms.security.exclude-matchers=/**

app.jwt.secret=secret1234567890qwertyuiopasdfghg
#app.jwt.expiration=604800

tencentcloud.cos.enabled=true
tencentcloud.cos.secret-id= AKIDcy3tTNXSdk27wXufOB9wSVFxd4E9drKW
tencentcloud.cos.secret-key= B9wbFfsGOrIUWKw01S6UrOfP1Uh17lJb
tencentcloud.cos.region= ap-shanghai
tencentcloud.cos.bucket= custom-1251067916
tencentcloud.cos.url-prefix= https://custom-1251067916.cos.ap-shanghai.myqcloud.com/
