server:
  port: 8200
spring:
  application:
    name: phecda-backend
  datasource:
    name: dataSource
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      driver-class-name: org.postgresql.Driver
  jackson:
    locale: zh_CN
    time-zone: Asia/Shanghai
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  messages:
    basename: i18n/validation
  cache:
    type: redis
    redis:
      key-prefix: "phecda:"
      use-key-prefix: true
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: triones-${spring.application.name}
  redis:
    redisson:
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: ${spring.data.redis.connect-timeout:10000}
          timeout: ${spring.data.redis.timeout:3000}
          retryAttempts: 3
          retryInterval: 1500
          password: ${spring.data.redis.password:null}
          subscriptionsPerConnection: 1
          clientName: null
          address: "redis://${spring.data.redis.host}:${spring.data.redis.port:6379}"
          subscriptionConnectionMinimumIdleSize: 0
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: ${spring.data.redis.pool.min-idle:0}
          connectionPoolSize: ${spring.data.redis.pool.max-idle:8}
          database: ${spring.data.redis.database:0}
          dnsMonitoringInterval: ${spring.data.redis.pool.time-between-eviction-runs:5000}
        threads: 16
        nettyThreads: 32
        transportMode: "NIO"



mybatis-plus:
  configuration:
    default-enum-type-handler: com.trionesdev.commons.mybatisplus.typehandlers.EnumTypeHandler
    map-underscore-to-camel-case: true
    log-prefix: dao.
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

triones:
  exception:
    resource-paths: i18n/error
  security:
    exclude-matchers: /**

