spring.datasource.url=jdbc:postgresql://xxx.xxx.xx:5432/xxx?stringtype=unspecified&TimeZone=UTC
spring.datasource.username=xxx
spring.datasource.password=xxx
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.validation-timeout=60000


#iotdb
spring.iotdb.host=127.0.0.1
spring.iotdb.port=6667
spring.iotdb.user=root
spring.iotdb.password=root
spring.iotdb.max-size=3
spring.iotdb.table-dialect=true

#redis
spring.data.redis.host=xxx
spring.data.redis.port=6379
spring.data.redis.database=11
spring.data.redis.password=xxx
spring.cache.redis.cache-null-values=false
spring.cache.redis.time-to-live=3600000
spring.cache.type=redis


#mqtt
spring.mqtt.client-id-prefix=phecda_
spring.mqtt.server-uri=tcp://xxx:1883
spring.mqtt.username=admin
spring.mqtt.password=public
spring.mqtt.automatic-reconnect=true
spring.mqtt.automatic-connect=false
spring.mqtt.topic-prefix=phecda-test

spring.kafka.consumer.bootstrap-servers=xxx:9092

triones.minio.enabled=true
triones.minio.access-key=xxx
triones.minio.secret-key=xxx
triones.minio.bucket=xxxx
triones.minio.endpoint=http://xxx:9000
triones.minio.url-prefix=http://xxx:9000

triones.message.type=redis

#zlmediakit
streaming.media.host=127.0.0.1
streaming.media.rtmp.port=1935
streaming.media.http.port=80

#logging.level.root=debug

triones.app.multi-tenant=false