spring.datasource.url=jdbc:postgresql://116.63.46.160:5432/phecda_dev?stringtype=unspecified&TimeZone=UTC
spring.datasource.username=product_developer
spring.datasource.password=product_developer
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.validation-timeout=60000

#iotdb
spring.iotdb.host=116.63.46.160
spring.iotdb.port=6667
spring.iotdb.user=root
spring.iotdb.password=root
spring.iotdb.max-size=3

#redis
spring.data.redis.host=116.63.46.160
spring.data.redis.port=6379
spring.data.redis.database=11
spring.data.redis.password=h@9Yq~8Ya@9Sn!0J
spring.cache.redis.cache-null-values=false
spring.cache.redis.time-to-live=3600000
spring.cache.type=redis


#mqtt
spring.mqtt.client-id-prefix=phecda_
spring.mqtt.server-uri=tcp://116.63.46.160:1883
spring.mqtt.username=admin
spring.mqtt.password=public
spring.mqtt.automatic-reconnect=true
spring.mqtt.automatic-connect=false
spring.mqtt.topic-prefix=phecda-test

spring.kafka.consumer.bootstrap-servers=116.63.46.160:9092

triones.minio.enabled=true
triones.minio.access-key=nJzmbBtFGzniUJJh
triones.minio.secret-key=unronarjljDqI8WPrMGEb8COmzDWK7Gc
triones.minio.bucket=belt-bucket
triones.minio.endpoint=http://116.63.46.160:9000
triones.minio.url-prefix=http://116.63.46.160:9000

#zlmediakit
streaming.media.host=127.0.0.1
streaming.media.rtmp.port=1935
streaming.media.http.port=80

#logging.level.root=debug