spring.datasource.url=jdbc:postgresql://116.63.46.160:5432/phecda_dev?stringtype=unspecified&TimeZone=UTC
spring.datasource.username=product_developer
spring.datasource.password=product_developer
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.validation-timeout=60000
#iotdb
spring.iotdb.host=116.63.46.160
spring.iotdb.port=6667
spring.iotdb.user=root
spring.iotdb.password=root
spring.iotdb.max-size=3
#redis
spring.redis.host=116.63.46.160
spring.redis.port=6379
spring.redis.database=11
spring.redis.password=h@9Yq~8Ya@9Sn!0J
#mqtt
spring.mqtt.client-id-prefix=phecda_
spring.mqtt.server-uri=tcp://116.63.46.160:1883
spring.mqtt.username=admin
spring.mqtt.password=public
spring.mqtt.automatic-reconnect=true
spring.mqtt.automatic-connect=false

#kafka
spring.kafka.bootstrap-servers=192.168.10.206:9092
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


app.jwt.secret=secret1234567890qwertyuiopasdfghg
#app.jwt.expiration=604800


minio.enabled=true
minio.access-key=nJzmbBtFGzniUJJh
minio.secret-key=unronarjljDqI8WPrMGEb8COmzDWK7Gc
minio.bucket=belt-bucket
minio.endpoint=http://116.63.46.160:9000
minio.url-prefix=http://116.63.46.160:9000
spring.cache.redis.key-prefix=phecda:
spring.cache.redis.use-key-prefix=true
#zlmediakit
streaming.media.host=127.0.0.1
streaming.media.rtmp.port=1935
streaming.media.http.port=80

#logging
#logging.level.root=debug